### ISSUE TITLE
Vector naming consistency

### ISSUE THREAD

**Issue by vurvdev** [nanos-world/nanos-world-lua-lib#13]
I noticed this from Vector4 being missing in the https://github.com/nanos-world/api, and wanted to bring this up before implementing it:

Right now we have ``Vector``, ``Vector2D`` and ``Vector4``.
Maybe the naming scheme should be normalized and be

``Vector2`` + ``Vector3`` + ``Vector4``

or

``Vector`` + ``Vector2`` + ``Vector4`` (To have ``Vector`` stand out since it'd be the most common usecase)

I can make a PR to rename/implement on the API, just need to know if it should stay the same or can be renamed

**Comment by gtnardy** [comment]
Yeah this pattern actually come from Unreal Engine, when I created them I managed to keep equal that

https://docs.unrealengine.com/5.0/en-US/BlueprintAPI/Math/Vector/
https://docs.unrealengine.com/5.0/en-US/BlueprintAPI/Math/Vector4/
https://docs.unrealengine.com/5.0/en-US/BlueprintAPI/Math/Vector2D/

Vector and Vector2D are "exposed" structs, but Vector4 is only used internally and could be renamed.

But honestly, I think Vector4 could be even completely deleted, as it's only being used for a single function (also as metatable inefficiently)

**Comment by vurvdev** [comment]
Hm that's an odd choice for UE, I see why it's named like that for nanos now though for familiarity for UE devs. I will just add the Vector4 definition to the https://github.com/nanos-world/api and whether it should be renamed/removed can be thought of later I guess
